// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface AuthenticationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.AuthenticationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * partner email from the partner portal website 
   * </pre>
   *
   * <code>string partner_email = 1;</code>
   * @return The partnerEmail.
   */
  java.lang.String getPartnerEmail();
  /**
   * <pre>
   * partner email from the partner portal website 
   * </pre>
   *
   * <code>string partner_email = 1;</code>
   * @return The bytes for partnerEmail.
   */
  com.google.protobuf.ByteString
      getPartnerEmailBytes();

  /**
   * <pre>
   * password the partner uses to login to the partner portal website
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * password the partner uses to login to the partner portal website
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
