// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface DeviceInventoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.DeviceInventoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * list of devices associated with the partner
   * </pre>
   *
   * <code>repeated .protos.DeviceInventoryResponse.Device devices = 1;</code>
   */
  java.util.List<com.emporiaenergy.protos.partnerapi.DeviceInventoryResponse.Device> 
      getDevicesList();
  /**
   * <pre>
   * list of devices associated with the partner
   * </pre>
   *
   * <code>repeated .protos.DeviceInventoryResponse.Device devices = 1;</code>
   */
  com.emporiaenergy.protos.partnerapi.DeviceInventoryResponse.Device getDevices(int index);
  /**
   * <pre>
   * list of devices associated with the partner
   * </pre>
   *
   * <code>repeated .protos.DeviceInventoryResponse.Device devices = 1;</code>
   */
  int getDevicesCount();
  /**
   * <pre>
   * list of devices associated with the partner
   * </pre>
   *
   * <code>repeated .protos.DeviceInventoryResponse.Device devices = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.protos.partnerapi.DeviceInventoryResponse.DeviceOrBuilder> 
      getDevicesOrBuilderList();
  /**
   * <pre>
   * list of devices associated with the partner
   * </pre>
   *
   * <code>repeated .protos.DeviceInventoryResponse.Device devices = 1;</code>
   */
  com.emporiaenergy.protos.partnerapi.DeviceInventoryResponse.DeviceOrBuilder getDevicesOrBuilder(
      int index);

  /**
   * <code>.protos.ResultStatus result_status = 100;</code>
   * @return The enum numeric value on the wire for resultStatus.
   */
  int getResultStatusValue();
  /**
   * <code>.protos.ResultStatus result_status = 100;</code>
   * @return The resultStatus.
   */
  com.emporiaenergy.protos.partnerapi.ResultStatus getResultStatus();
}
