// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

/**
 * <pre>
 * Get historical usage for the specified time range and scale
 * Usage is returned for each of the specified devices, allowing usage data to be queried 
 * for a single device or group of devices in a single call. 
 * </pre>
 *
 * Protobuf type {@code protos.DeviceUsageRequest}
 */
public final class DeviceUsageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.DeviceUsageRequest)
    DeviceUsageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceUsageRequest.newBuilder() to construct.
  private DeviceUsageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceUsageRequest() {
    authToken_ = "";
    scale_ = "";
    channels_ = 0;
    manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceUsageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceUsageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            authToken_ = s;
            break;
          }
          case 16: {

            startEpochSeconds_ = input.readUInt64();
            break;
          }
          case 24: {

            endEpochSeconds_ = input.readUInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            scale_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            channels_ = rawValue;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              manufacturerDeviceId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            manufacturerDeviceId_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = manufacturerDeviceId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceUsageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceUsageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.class, com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.Builder.class);
  }

  public static final int AUTH_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object authToken_;
  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  @java.lang.Override
  public java.lang.String getAuthToken() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authToken_ = s;
      return s;
    }
  }
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthTokenBytes() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_EPOCH_SECONDS_FIELD_NUMBER = 2;
  private long startEpochSeconds_;
  /**
   * <pre>
   * start and end are specified as seconds since epoch (January 1, 1970) in the UTC timezone.
   * </pre>
   *
   * <code>uint64 start_epoch_seconds = 2;</code>
   * @return The startEpochSeconds.
   */
  @java.lang.Override
  public long getStartEpochSeconds() {
    return startEpochSeconds_;
  }

  public static final int END_EPOCH_SECONDS_FIELD_NUMBER = 3;
  private long endEpochSeconds_;
  /**
   * <code>uint64 end_epoch_seconds = 3;</code>
   * @return The endEpochSeconds.
   */
  @java.lang.Override
  public long getEndEpochSeconds() {
    return endEpochSeconds_;
  }

  public static final int SCALE_FIELD_NUMBER = 4;
  private volatile java.lang.Object scale_;
  /**
   * <pre>
   * What resolution data should be fetched?  Historical data is returned in buckets with the 
   * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
   * </pre>
   *
   * <code>string scale = 4;</code>
   * @return The scale.
   */
  @java.lang.Override
  public java.lang.String getScale() {
    java.lang.Object ref = scale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scale_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * What resolution data should be fetched?  Historical data is returned in buckets with the 
   * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
   * </pre>
   *
   * <code>string scale = 4;</code>
   * @return The bytes for scale.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScaleBytes() {
    java.lang.Object ref = scale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNELS_FIELD_NUMBER = 5;
  private int channels_;
  /**
   * <pre>
   * which channels of data should be fetched?
   * </pre>
   *
   * <code>.protos.UsageChannel channels = 5;</code>
   * @return The enum numeric value on the wire for channels.
   */
  @java.lang.Override public int getChannelsValue() {
    return channels_;
  }
  /**
   * <pre>
   * which channels of data should be fetched?
   * </pre>
   *
   * <code>.protos.UsageChannel channels = 5;</code>
   * @return The channels.
   */
  @java.lang.Override public com.emporiaenergy.protos.partnerapi.UsageChannel getChannels() {
    @SuppressWarnings("deprecation")
    com.emporiaenergy.protos.partnerapi.UsageChannel result = com.emporiaenergy.protos.partnerapi.UsageChannel.valueOf(channels_);
    return result == null ? com.emporiaenergy.protos.partnerapi.UsageChannel.UNRECOGNIZED : result;
  }

  public static final int MANUFACTURER_DEVICE_ID_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList manufacturerDeviceId_;
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @return A list containing the manufacturerDeviceId.
   */
  public com.google.protobuf.ProtocolStringList
      getManufacturerDeviceIdList() {
    return manufacturerDeviceId_;
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @return The count of manufacturerDeviceId.
   */
  public int getManufacturerDeviceIdCount() {
    return manufacturerDeviceId_.size();
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @param index The index of the element to return.
   * @return The manufacturerDeviceId at the given index.
   */
  public java.lang.String getManufacturerDeviceId(int index) {
    return manufacturerDeviceId_.get(index);
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the manufacturerDeviceId at the given index.
   */
  public com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes(int index) {
    return manufacturerDeviceId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authToken_);
    }
    if (startEpochSeconds_ != 0L) {
      output.writeUInt64(2, startEpochSeconds_);
    }
    if (endEpochSeconds_ != 0L) {
      output.writeUInt64(3, endEpochSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scale_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scale_);
    }
    if (channels_ != com.emporiaenergy.protos.partnerapi.UsageChannel.MAINS.getNumber()) {
      output.writeEnum(5, channels_);
    }
    for (int i = 0; i < manufacturerDeviceId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, manufacturerDeviceId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authToken_);
    }
    if (startEpochSeconds_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, startEpochSeconds_);
    }
    if (endEpochSeconds_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, endEpochSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scale_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, scale_);
    }
    if (channels_ != com.emporiaenergy.protos.partnerapi.UsageChannel.MAINS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, channels_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < manufacturerDeviceId_.size(); i++) {
        dataSize += computeStringSizeNoTag(manufacturerDeviceId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getManufacturerDeviceIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.protos.partnerapi.DeviceUsageRequest)) {
      return super.equals(obj);
    }
    com.emporiaenergy.protos.partnerapi.DeviceUsageRequest other = (com.emporiaenergy.protos.partnerapi.DeviceUsageRequest) obj;

    if (!getAuthToken()
        .equals(other.getAuthToken())) return false;
    if (getStartEpochSeconds()
        != other.getStartEpochSeconds()) return false;
    if (getEndEpochSeconds()
        != other.getEndEpochSeconds()) return false;
    if (!getScale()
        .equals(other.getScale())) return false;
    if (channels_ != other.channels_) return false;
    if (!getManufacturerDeviceIdList()
        .equals(other.getManufacturerDeviceIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTH_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAuthToken().hashCode();
    hash = (37 * hash) + START_EPOCH_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartEpochSeconds());
    hash = (37 * hash) + END_EPOCH_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndEpochSeconds());
    hash = (37 * hash) + SCALE_FIELD_NUMBER;
    hash = (53 * hash) + getScale().hashCode();
    hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
    hash = (53 * hash) + channels_;
    if (getManufacturerDeviceIdCount() > 0) {
      hash = (37 * hash) + MANUFACTURER_DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerDeviceIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.protos.partnerapi.DeviceUsageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get historical usage for the specified time range and scale
   * Usage is returned for each of the specified devices, allowing usage data to be queried 
   * for a single device or group of devices in a single call. 
   * </pre>
   *
   * Protobuf type {@code protos.DeviceUsageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.DeviceUsageRequest)
      com.emporiaenergy.protos.partnerapi.DeviceUsageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceUsageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceUsageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.class, com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.Builder.class);
    }

    // Construct using com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      authToken_ = "";

      startEpochSeconds_ = 0L;

      endEpochSeconds_ = 0L;

      scale_ = "";

      channels_ = 0;

      manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceUsageRequest_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceUsageRequest getDefaultInstanceForType() {
      return com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceUsageRequest build() {
      com.emporiaenergy.protos.partnerapi.DeviceUsageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceUsageRequest buildPartial() {
      com.emporiaenergy.protos.partnerapi.DeviceUsageRequest result = new com.emporiaenergy.protos.partnerapi.DeviceUsageRequest(this);
      int from_bitField0_ = bitField0_;
      result.authToken_ = authToken_;
      result.startEpochSeconds_ = startEpochSeconds_;
      result.endEpochSeconds_ = endEpochSeconds_;
      result.scale_ = scale_;
      result.channels_ = channels_;
      if (((bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = manufacturerDeviceId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.manufacturerDeviceId_ = manufacturerDeviceId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.protos.partnerapi.DeviceUsageRequest) {
        return mergeFrom((com.emporiaenergy.protos.partnerapi.DeviceUsageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.protos.partnerapi.DeviceUsageRequest other) {
      if (other == com.emporiaenergy.protos.partnerapi.DeviceUsageRequest.getDefaultInstance()) return this;
      if (!other.getAuthToken().isEmpty()) {
        authToken_ = other.authToken_;
        onChanged();
      }
      if (other.getStartEpochSeconds() != 0L) {
        setStartEpochSeconds(other.getStartEpochSeconds());
      }
      if (other.getEndEpochSeconds() != 0L) {
        setEndEpochSeconds(other.getEndEpochSeconds());
      }
      if (!other.getScale().isEmpty()) {
        scale_ = other.scale_;
        onChanged();
      }
      if (other.channels_ != 0) {
        setChannelsValue(other.getChannelsValue());
      }
      if (!other.manufacturerDeviceId_.isEmpty()) {
        if (manufacturerDeviceId_.isEmpty()) {
          manufacturerDeviceId_ = other.manufacturerDeviceId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureManufacturerDeviceIdIsMutable();
          manufacturerDeviceId_.addAll(other.manufacturerDeviceId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.protos.partnerapi.DeviceUsageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.protos.partnerapi.DeviceUsageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object authToken_ = "";
    /**
     * <code>string auth_token = 1;</code>
     * @return The authToken.
     */
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return The bytes for authToken.
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthToken() {
      
      authToken_ = getDefaultInstance().getAuthToken();
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The bytes for authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authToken_ = value;
      onChanged();
      return this;
    }

    private long startEpochSeconds_ ;
    /**
     * <pre>
     * start and end are specified as seconds since epoch (January 1, 1970) in the UTC timezone.
     * </pre>
     *
     * <code>uint64 start_epoch_seconds = 2;</code>
     * @return The startEpochSeconds.
     */
    @java.lang.Override
    public long getStartEpochSeconds() {
      return startEpochSeconds_;
    }
    /**
     * <pre>
     * start and end are specified as seconds since epoch (January 1, 1970) in the UTC timezone.
     * </pre>
     *
     * <code>uint64 start_epoch_seconds = 2;</code>
     * @param value The startEpochSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setStartEpochSeconds(long value) {
      
      startEpochSeconds_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * start and end are specified as seconds since epoch (January 1, 1970) in the UTC timezone.
     * </pre>
     *
     * <code>uint64 start_epoch_seconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartEpochSeconds() {
      
      startEpochSeconds_ = 0L;
      onChanged();
      return this;
    }

    private long endEpochSeconds_ ;
    /**
     * <code>uint64 end_epoch_seconds = 3;</code>
     * @return The endEpochSeconds.
     */
    @java.lang.Override
    public long getEndEpochSeconds() {
      return endEpochSeconds_;
    }
    /**
     * <code>uint64 end_epoch_seconds = 3;</code>
     * @param value The endEpochSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setEndEpochSeconds(long value) {
      
      endEpochSeconds_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 end_epoch_seconds = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndEpochSeconds() {
      
      endEpochSeconds_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object scale_ = "";
    /**
     * <pre>
     * What resolution data should be fetched?  Historical data is returned in buckets with the 
     * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
     * </pre>
     *
     * <code>string scale = 4;</code>
     * @return The scale.
     */
    public java.lang.String getScale() {
      java.lang.Object ref = scale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * What resolution data should be fetched?  Historical data is returned in buckets with the 
     * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
     * </pre>
     *
     * <code>string scale = 4;</code>
     * @return The bytes for scale.
     */
    public com.google.protobuf.ByteString
        getScaleBytes() {
      java.lang.Object ref = scale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * What resolution data should be fetched?  Historical data is returned in buckets with the 
     * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
     * </pre>
     *
     * <code>string scale = 4;</code>
     * @param value The scale to set.
     * @return This builder for chaining.
     */
    public Builder setScale(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scale_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What resolution data should be fetched?  Historical data is returned in buckets with the 
     * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
     * </pre>
     *
     * <code>string scale = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScale() {
      
      scale_ = getDefaultInstance().getScale();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What resolution data should be fetched?  Historical data is returned in buckets with the 
     * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
     * </pre>
     *
     * <code>string scale = 4;</code>
     * @param value The bytes for scale to set.
     * @return This builder for chaining.
     */
    public Builder setScaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scale_ = value;
      onChanged();
      return this;
    }

    private int channels_ = 0;
    /**
     * <pre>
     * which channels of data should be fetched?
     * </pre>
     *
     * <code>.protos.UsageChannel channels = 5;</code>
     * @return The enum numeric value on the wire for channels.
     */
    @java.lang.Override public int getChannelsValue() {
      return channels_;
    }
    /**
     * <pre>
     * which channels of data should be fetched?
     * </pre>
     *
     * <code>.protos.UsageChannel channels = 5;</code>
     * @param value The enum numeric value on the wire for channels to set.
     * @return This builder for chaining.
     */
    public Builder setChannelsValue(int value) {
      
      channels_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * which channels of data should be fetched?
     * </pre>
     *
     * <code>.protos.UsageChannel channels = 5;</code>
     * @return The channels.
     */
    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.UsageChannel getChannels() {
      @SuppressWarnings("deprecation")
      com.emporiaenergy.protos.partnerapi.UsageChannel result = com.emporiaenergy.protos.partnerapi.UsageChannel.valueOf(channels_);
      return result == null ? com.emporiaenergy.protos.partnerapi.UsageChannel.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * which channels of data should be fetched?
     * </pre>
     *
     * <code>.protos.UsageChannel channels = 5;</code>
     * @param value The channels to set.
     * @return This builder for chaining.
     */
    public Builder setChannels(com.emporiaenergy.protos.partnerapi.UsageChannel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      channels_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * which channels of data should be fetched?
     * </pre>
     *
     * <code>.protos.UsageChannel channels = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannels() {
      
      channels_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureManufacturerDeviceIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = new com.google.protobuf.LazyStringArrayList(manufacturerDeviceId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @return A list containing the manufacturerDeviceId.
     */
    public com.google.protobuf.ProtocolStringList
        getManufacturerDeviceIdList() {
      return manufacturerDeviceId_.getUnmodifiableView();
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @return The count of manufacturerDeviceId.
     */
    public int getManufacturerDeviceIdCount() {
      return manufacturerDeviceId_.size();
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param index The index of the element to return.
     * @return The manufacturerDeviceId at the given index.
     */
    public java.lang.String getManufacturerDeviceId(int index) {
      return manufacturerDeviceId_.get(index);
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the manufacturerDeviceId at the given index.
     */
    public com.google.protobuf.ByteString
        getManufacturerDeviceIdBytes(int index) {
      return manufacturerDeviceId_.getByteString(index);
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param index The index to set the value at.
     * @param value The manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param value The manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addManufacturerDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param values The manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addAllManufacturerDeviceId(
        java.lang.Iterable<java.lang.String> values) {
      ensureManufacturerDeviceIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, manufacturerDeviceId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerDeviceId() {
      manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 6;</code>
     * @param value The bytes of the manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addManufacturerDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.DeviceUsageRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.DeviceUsageRequest)
  private static final com.emporiaenergy.protos.partnerapi.DeviceUsageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.protos.partnerapi.DeviceUsageRequest();
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceUsageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceUsageRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeviceUsageRequest>() {
    @java.lang.Override
    public DeviceUsageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceUsageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceUsageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceUsageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.DeviceUsageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

