// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

/**
 * <pre>
 * request information on the devices associated to the partner
 * </pre>
 *
 * Protobuf type {@code protos.DeviceInventoryRequest}
 */
public final class DeviceInventoryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.DeviceInventoryRequest)
    DeviceInventoryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceInventoryRequest.newBuilder() to construct.
  private DeviceInventoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceInventoryRequest() {
    authToken_ = "";
    customerEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceInventoryRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceInventoryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            authToken_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              customerEmails_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            customerEmails_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        customerEmails_ = customerEmails_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceInventoryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceInventoryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.class, com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.Builder.class);
  }

  public static final int AUTH_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object authToken_;
  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  @java.lang.Override
  public java.lang.String getAuthToken() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authToken_ = s;
      return s;
    }
  }
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthTokenBytes() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_EMAILS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList customerEmails_;
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @return A list containing the customerEmails.
   */
  public com.google.protobuf.ProtocolStringList
      getCustomerEmailsList() {
    return customerEmails_;
  }
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @return The count of customerEmails.
   */
  public int getCustomerEmailsCount() {
    return customerEmails_.size();
  }
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @param index The index of the element to return.
   * @return The customerEmails at the given index.
   */
  public java.lang.String getCustomerEmails(int index) {
    return customerEmails_.get(index);
  }
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the customerEmails at the given index.
   */
  public com.google.protobuf.ByteString
      getCustomerEmailsBytes(int index) {
    return customerEmails_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authToken_);
    }
    for (int i = 0; i < customerEmails_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerEmails_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authToken_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < customerEmails_.size(); i++) {
        dataSize += computeStringSizeNoTag(customerEmails_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCustomerEmailsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest)) {
      return super.equals(obj);
    }
    com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest other = (com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest) obj;

    if (!getAuthToken()
        .equals(other.getAuthToken())) return false;
    if (!getCustomerEmailsList()
        .equals(other.getCustomerEmailsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTH_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAuthToken().hashCode();
    if (getCustomerEmailsCount() > 0) {
      hash = (37 * hash) + CUSTOMER_EMAILS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerEmailsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * request information on the devices associated to the partner
   * </pre>
   *
   * Protobuf type {@code protos.DeviceInventoryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.DeviceInventoryRequest)
      com.emporiaenergy.protos.partnerapi.DeviceInventoryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceInventoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceInventoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.class, com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.Builder.class);
    }

    // Construct using com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      authToken_ = "";

      customerEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceInventoryRequest_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest getDefaultInstanceForType() {
      return com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest build() {
      com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest buildPartial() {
      com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest result = new com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest(this);
      int from_bitField0_ = bitField0_;
      result.authToken_ = authToken_;
      if (((bitField0_ & 0x00000001) != 0)) {
        customerEmails_ = customerEmails_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.customerEmails_ = customerEmails_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest) {
        return mergeFrom((com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest other) {
      if (other == com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest.getDefaultInstance()) return this;
      if (!other.getAuthToken().isEmpty()) {
        authToken_ = other.authToken_;
        onChanged();
      }
      if (!other.customerEmails_.isEmpty()) {
        if (customerEmails_.isEmpty()) {
          customerEmails_ = other.customerEmails_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCustomerEmailsIsMutable();
          customerEmails_.addAll(other.customerEmails_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object authToken_ = "";
    /**
     * <code>string auth_token = 1;</code>
     * @return The authToken.
     */
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return The bytes for authToken.
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthToken() {
      
      authToken_ = getDefaultInstance().getAuthToken();
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The bytes for authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authToken_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList customerEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCustomerEmailsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        customerEmails_ = new com.google.protobuf.LazyStringArrayList(customerEmails_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @return A list containing the customerEmails.
     */
    public com.google.protobuf.ProtocolStringList
        getCustomerEmailsList() {
      return customerEmails_.getUnmodifiableView();
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @return The count of customerEmails.
     */
    public int getCustomerEmailsCount() {
      return customerEmails_.size();
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param index The index of the element to return.
     * @return The customerEmails at the given index.
     */
    public java.lang.String getCustomerEmails(int index) {
      return customerEmails_.get(index);
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the customerEmails at the given index.
     */
    public com.google.protobuf.ByteString
        getCustomerEmailsBytes(int index) {
      return customerEmails_.getByteString(index);
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param index The index to set the value at.
     * @param value The customerEmails to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerEmails(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomerEmailsIsMutable();
      customerEmails_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param value The customerEmails to add.
     * @return This builder for chaining.
     */
    public Builder addCustomerEmails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomerEmailsIsMutable();
      customerEmails_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param values The customerEmails to add.
     * @return This builder for chaining.
     */
    public Builder addAllCustomerEmails(
        java.lang.Iterable<java.lang.String> values) {
      ensureCustomerEmailsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, customerEmails_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerEmails() {
      customerEmails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If empty, return all devices associated with partner
     * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
     * </pre>
     *
     * <code>repeated string customer_emails = 2;</code>
     * @param value The bytes of the customerEmails to add.
     * @return This builder for chaining.
     */
    public Builder addCustomerEmailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCustomerEmailsIsMutable();
      customerEmails_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.DeviceInventoryRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.DeviceInventoryRequest)
  private static final com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest();
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceInventoryRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeviceInventoryRequest>() {
    @java.lang.Override
    public DeviceInventoryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceInventoryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceInventoryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceInventoryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.DeviceInventoryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

