// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

/**
 * <pre>
 * Query current outlet state for one or more partner outlet devices. 
 * Device IDs are specified in query command, allowing state to be queried for multiple outlets in a single call.  
 * </pre>
 *
 * Protobuf type {@code protos.DeviceListRequest}
 */
public final class DeviceListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.DeviceListRequest)
    DeviceListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceListRequest.newBuilder() to construct.
  private DeviceListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceListRequest() {
    authToken_ = "";
    manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceListRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            authToken_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              manufacturerDeviceId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            manufacturerDeviceId_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = manufacturerDeviceId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceListRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.protos.partnerapi.DeviceListRequest.class, com.emporiaenergy.protos.partnerapi.DeviceListRequest.Builder.class);
  }

  public static final int AUTH_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object authToken_;
  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  @java.lang.Override
  public java.lang.String getAuthToken() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authToken_ = s;
      return s;
    }
  }
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthTokenBytes() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANUFACTURER_DEVICE_ID_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList manufacturerDeviceId_;
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 2;</code>
   * @return A list containing the manufacturerDeviceId.
   */
  public com.google.protobuf.ProtocolStringList
      getManufacturerDeviceIdList() {
    return manufacturerDeviceId_;
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 2;</code>
   * @return The count of manufacturerDeviceId.
   */
  public int getManufacturerDeviceIdCount() {
    return manufacturerDeviceId_.size();
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 2;</code>
   * @param index The index of the element to return.
   * @return The manufacturerDeviceId at the given index.
   */
  public java.lang.String getManufacturerDeviceId(int index) {
    return manufacturerDeviceId_.get(index);
  }
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the manufacturerDeviceId at the given index.
   */
  public com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes(int index) {
    return manufacturerDeviceId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authToken_);
    }
    for (int i = 0; i < manufacturerDeviceId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, manufacturerDeviceId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authToken_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < manufacturerDeviceId_.size(); i++) {
        dataSize += computeStringSizeNoTag(manufacturerDeviceId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getManufacturerDeviceIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.protos.partnerapi.DeviceListRequest)) {
      return super.equals(obj);
    }
    com.emporiaenergy.protos.partnerapi.DeviceListRequest other = (com.emporiaenergy.protos.partnerapi.DeviceListRequest) obj;

    if (!getAuthToken()
        .equals(other.getAuthToken())) return false;
    if (!getManufacturerDeviceIdList()
        .equals(other.getManufacturerDeviceIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTH_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAuthToken().hashCode();
    if (getManufacturerDeviceIdCount() > 0) {
      hash = (37 * hash) + MANUFACTURER_DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerDeviceIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.protos.partnerapi.DeviceListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Query current outlet state for one or more partner outlet devices. 
   * Device IDs are specified in query command, allowing state to be queried for multiple outlets in a single call.  
   * </pre>
   *
   * Protobuf type {@code protos.DeviceListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.DeviceListRequest)
      com.emporiaenergy.protos.partnerapi.DeviceListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.protos.partnerapi.DeviceListRequest.class, com.emporiaenergy.protos.partnerapi.DeviceListRequest.Builder.class);
    }

    // Construct using com.emporiaenergy.protos.partnerapi.DeviceListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      authToken_ = "";

      manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_DeviceListRequest_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceListRequest getDefaultInstanceForType() {
      return com.emporiaenergy.protos.partnerapi.DeviceListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceListRequest build() {
      com.emporiaenergy.protos.partnerapi.DeviceListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.DeviceListRequest buildPartial() {
      com.emporiaenergy.protos.partnerapi.DeviceListRequest result = new com.emporiaenergy.protos.partnerapi.DeviceListRequest(this);
      int from_bitField0_ = bitField0_;
      result.authToken_ = authToken_;
      if (((bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = manufacturerDeviceId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.manufacturerDeviceId_ = manufacturerDeviceId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.protos.partnerapi.DeviceListRequest) {
        return mergeFrom((com.emporiaenergy.protos.partnerapi.DeviceListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.protos.partnerapi.DeviceListRequest other) {
      if (other == com.emporiaenergy.protos.partnerapi.DeviceListRequest.getDefaultInstance()) return this;
      if (!other.getAuthToken().isEmpty()) {
        authToken_ = other.authToken_;
        onChanged();
      }
      if (!other.manufacturerDeviceId_.isEmpty()) {
        if (manufacturerDeviceId_.isEmpty()) {
          manufacturerDeviceId_ = other.manufacturerDeviceId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureManufacturerDeviceIdIsMutable();
          manufacturerDeviceId_.addAll(other.manufacturerDeviceId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.protos.partnerapi.DeviceListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.protos.partnerapi.DeviceListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object authToken_ = "";
    /**
     * <code>string auth_token = 1;</code>
     * @return The authToken.
     */
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return The bytes for authToken.
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthToken() {
      
      authToken_ = getDefaultInstance().getAuthToken();
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The bytes for authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authToken_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureManufacturerDeviceIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        manufacturerDeviceId_ = new com.google.protobuf.LazyStringArrayList(manufacturerDeviceId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @return A list containing the manufacturerDeviceId.
     */
    public com.google.protobuf.ProtocolStringList
        getManufacturerDeviceIdList() {
      return manufacturerDeviceId_.getUnmodifiableView();
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @return The count of manufacturerDeviceId.
     */
    public int getManufacturerDeviceIdCount() {
      return manufacturerDeviceId_.size();
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param index The index of the element to return.
     * @return The manufacturerDeviceId at the given index.
     */
    public java.lang.String getManufacturerDeviceId(int index) {
      return manufacturerDeviceId_.get(index);
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the manufacturerDeviceId at the given index.
     */
    public com.google.protobuf.ByteString
        getManufacturerDeviceIdBytes(int index) {
      return manufacturerDeviceId_.getByteString(index);
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param index The index to set the value at.
     * @param value The manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param value The manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addManufacturerDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param values The manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addAllManufacturerDeviceId(
        java.lang.Iterable<java.lang.String> values) {
      ensureManufacturerDeviceIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, manufacturerDeviceId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerDeviceId() {
      manufacturerDeviceId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of device ids, this must be populated or the response will be empty
     * </pre>
     *
     * <code>repeated string manufacturer_device_id = 2;</code>
     * @param value The bytes of the manufacturerDeviceId to add.
     * @return This builder for chaining.
     */
    public Builder addManufacturerDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureManufacturerDeviceIdIsMutable();
      manufacturerDeviceId_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.DeviceListRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.DeviceListRequest)
  private static final com.emporiaenergy.protos.partnerapi.DeviceListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.protos.partnerapi.DeviceListRequest();
  }

  public static com.emporiaenergy.protos.partnerapi.DeviceListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceListRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeviceListRequest>() {
    @java.lang.Override
    public DeviceListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.DeviceListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

