// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface DeviceUsageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.DeviceUsageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();

  /**
   * <pre>
   * start and end are specified as seconds since epoch (January 1, 1970) in the UTC timezone.
   * </pre>
   *
   * <code>uint64 start_epoch_seconds = 2;</code>
   * @return The startEpochSeconds.
   */
  long getStartEpochSeconds();

  /**
   * <code>uint64 end_epoch_seconds = 3;</code>
   * @return The endEpochSeconds.
   */
  long getEndEpochSeconds();

  /**
   * <pre>
   * What resolution data should be fetched?  Historical data is returned in buckets with the 
   * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
   * </pre>
   *
   * <code>string scale = 4;</code>
   * @return The scale.
   */
  java.lang.String getScale();
  /**
   * <pre>
   * What resolution data should be fetched?  Historical data is returned in buckets with the 
   * requested scale, e.g., the 15MIN scale returns buckets representing 15 minutes of energy usage
   * </pre>
   *
   * <code>string scale = 4;</code>
   * @return The bytes for scale.
   */
  com.google.protobuf.ByteString
      getScaleBytes();

  /**
   * <pre>
   * which channels of data should be fetched?
   * </pre>
   *
   * <code>.protos.UsageChannel channels = 5;</code>
   * @return The enum numeric value on the wire for channels.
   */
  int getChannelsValue();
  /**
   * <pre>
   * which channels of data should be fetched?
   * </pre>
   *
   * <code>.protos.UsageChannel channels = 5;</code>
   * @return The channels.
   */
  com.emporiaenergy.protos.partnerapi.UsageChannel getChannels();

  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @return A list containing the manufacturerDeviceId.
   */
  java.util.List<java.lang.String>
      getManufacturerDeviceIdList();
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @return The count of manufacturerDeviceId.
   */
  int getManufacturerDeviceIdCount();
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @param index The index of the element to return.
   * @return The manufacturerDeviceId at the given index.
   */
  java.lang.String getManufacturerDeviceId(int index);
  /**
   * <pre>
   * list of device ids, this must be populated or the response will be empty
   * </pre>
   *
   * <code>repeated string manufacturer_device_id = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the manufacturerDeviceId at the given index.
   */
  com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes(int index);
}
