// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface DeviceInventoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.DeviceInventoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();

  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @return A list containing the customerEmails.
   */
  java.util.List<java.lang.String>
      getCustomerEmailsList();
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @return The count of customerEmails.
   */
  int getCustomerEmailsCount();
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @param index The index of the element to return.
   * @return The customerEmails at the given index.
   */
  java.lang.String getCustomerEmails(int index);
  /**
   * <pre>
   * If empty, return all devices associated with partner
   * if not empty, return all the devices associated to the partner AND to the specified customer email(s) 
   * </pre>
   *
   * <code>repeated string customer_emails = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the customerEmails at the given index.
   */
  com.google.protobuf.ByteString
      getCustomerEmailsBytes(int index);
}
