// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface DeviceUsageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.DeviceUsageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.DeviceUsageResponse.DeviceUsage device_usage = 1;</code>
   */
  java.util.List<com.emporiaenergy.protos.partnerapi.DeviceUsageResponse.DeviceUsage> 
      getDeviceUsageList();
  /**
   * <code>repeated .protos.DeviceUsageResponse.DeviceUsage device_usage = 1;</code>
   */
  com.emporiaenergy.protos.partnerapi.DeviceUsageResponse.DeviceUsage getDeviceUsage(int index);
  /**
   * <code>repeated .protos.DeviceUsageResponse.DeviceUsage device_usage = 1;</code>
   */
  int getDeviceUsageCount();
  /**
   * <code>repeated .protos.DeviceUsageResponse.DeviceUsage device_usage = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.protos.partnerapi.DeviceUsageResponse.DeviceUsageOrBuilder> 
      getDeviceUsageOrBuilderList();
  /**
   * <code>repeated .protos.DeviceUsageResponse.DeviceUsage device_usage = 1;</code>
   */
  com.emporiaenergy.protos.partnerapi.DeviceUsageResponse.DeviceUsageOrBuilder getDeviceUsageOrBuilder(
      int index);

  /**
   * <code>.protos.ResultStatus result_status = 100;</code>
   * @return The enum numeric value on the wire for resultStatus.
   */
  int getResultStatusValue();
  /**
   * <code>.protos.ResultStatus result_status = 100;</code>
   * @return The resultStatus.
   */
  com.emporiaenergy.protos.partnerapi.ResultStatus getResultStatus();
}
