// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

/**
 * <pre>
 * Used by the SetOutletStatus method to turn an Outlet on or off
 * </pre>
 *
 * Protobuf type {@code protos.OutletStatusRequest}
 */
public final class OutletStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.OutletStatusRequest)
    OutletStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutletStatusRequest.newBuilder() to construct.
  private OutletStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutletStatusRequest() {
    authToken_ = "";
    outletStatus_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OutletStatusRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutletStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            authToken_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              outletStatus_ = new java.util.ArrayList<com.emporiaenergy.protos.partnerapi.OutletStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            outletStatus_.add(
                input.readMessage(com.emporiaenergy.protos.partnerapi.OutletStatus.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        outletStatus_ = java.util.Collections.unmodifiableList(outletStatus_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_OutletStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_OutletStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.protos.partnerapi.OutletStatusRequest.class, com.emporiaenergy.protos.partnerapi.OutletStatusRequest.Builder.class);
  }

  public static final int AUTH_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object authToken_;
  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  @java.lang.Override
  public java.lang.String getAuthToken() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authToken_ = s;
      return s;
    }
  }
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthTokenBytes() {
    java.lang.Object ref = authToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTLET_STATUS_FIELD_NUMBER = 2;
  private java.util.List<com.emporiaenergy.protos.partnerapi.OutletStatus> outletStatus_;
  /**
   * <pre>
   * should the outlet be set to on or off?
   * </pre>
   *
   * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.emporiaenergy.protos.partnerapi.OutletStatus> getOutletStatusList() {
    return outletStatus_;
  }
  /**
   * <pre>
   * should the outlet be set to on or off?
   * </pre>
   *
   * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder> 
      getOutletStatusOrBuilderList() {
    return outletStatus_;
  }
  /**
   * <pre>
   * should the outlet be set to on or off?
   * </pre>
   *
   * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
   */
  @java.lang.Override
  public int getOutletStatusCount() {
    return outletStatus_.size();
  }
  /**
   * <pre>
   * should the outlet be set to on or off?
   * </pre>
   *
   * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.OutletStatus getOutletStatus(int index) {
    return outletStatus_.get(index);
  }
  /**
   * <pre>
   * should the outlet be set to on or off?
   * </pre>
   *
   * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder getOutletStatusOrBuilder(
      int index) {
    return outletStatus_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authToken_);
    }
    for (int i = 0; i < outletStatus_.size(); i++) {
      output.writeMessage(2, outletStatus_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authToken_);
    }
    for (int i = 0; i < outletStatus_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, outletStatus_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.protos.partnerapi.OutletStatusRequest)) {
      return super.equals(obj);
    }
    com.emporiaenergy.protos.partnerapi.OutletStatusRequest other = (com.emporiaenergy.protos.partnerapi.OutletStatusRequest) obj;

    if (!getAuthToken()
        .equals(other.getAuthToken())) return false;
    if (!getOutletStatusList()
        .equals(other.getOutletStatusList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTH_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAuthToken().hashCode();
    if (getOutletStatusCount() > 0) {
      hash = (37 * hash) + OUTLET_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getOutletStatusList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.protos.partnerapi.OutletStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Used by the SetOutletStatus method to turn an Outlet on or off
   * </pre>
   *
   * Protobuf type {@code protos.OutletStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.OutletStatusRequest)
      com.emporiaenergy.protos.partnerapi.OutletStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_OutletStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_OutletStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.protos.partnerapi.OutletStatusRequest.class, com.emporiaenergy.protos.partnerapi.OutletStatusRequest.Builder.class);
    }

    // Construct using com.emporiaenergy.protos.partnerapi.OutletStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOutletStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      authToken_ = "";

      if (outletStatusBuilder_ == null) {
        outletStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        outletStatusBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.protos.partnerapi.PartnerApiProto.internal_static_protos_OutletStatusRequest_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.OutletStatusRequest getDefaultInstanceForType() {
      return com.emporiaenergy.protos.partnerapi.OutletStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.OutletStatusRequest build() {
      com.emporiaenergy.protos.partnerapi.OutletStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.protos.partnerapi.OutletStatusRequest buildPartial() {
      com.emporiaenergy.protos.partnerapi.OutletStatusRequest result = new com.emporiaenergy.protos.partnerapi.OutletStatusRequest(this);
      int from_bitField0_ = bitField0_;
      result.authToken_ = authToken_;
      if (outletStatusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          outletStatus_ = java.util.Collections.unmodifiableList(outletStatus_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.outletStatus_ = outletStatus_;
      } else {
        result.outletStatus_ = outletStatusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.protos.partnerapi.OutletStatusRequest) {
        return mergeFrom((com.emporiaenergy.protos.partnerapi.OutletStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.protos.partnerapi.OutletStatusRequest other) {
      if (other == com.emporiaenergy.protos.partnerapi.OutletStatusRequest.getDefaultInstance()) return this;
      if (!other.getAuthToken().isEmpty()) {
        authToken_ = other.authToken_;
        onChanged();
      }
      if (outletStatusBuilder_ == null) {
        if (!other.outletStatus_.isEmpty()) {
          if (outletStatus_.isEmpty()) {
            outletStatus_ = other.outletStatus_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOutletStatusIsMutable();
            outletStatus_.addAll(other.outletStatus_);
          }
          onChanged();
        }
      } else {
        if (!other.outletStatus_.isEmpty()) {
          if (outletStatusBuilder_.isEmpty()) {
            outletStatusBuilder_.dispose();
            outletStatusBuilder_ = null;
            outletStatus_ = other.outletStatus_;
            bitField0_ = (bitField0_ & ~0x00000001);
            outletStatusBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOutletStatusFieldBuilder() : null;
          } else {
            outletStatusBuilder_.addAllMessages(other.outletStatus_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.protos.partnerapi.OutletStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.protos.partnerapi.OutletStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object authToken_ = "";
    /**
     * <code>string auth_token = 1;</code>
     * @return The authToken.
     */
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return The bytes for authToken.
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthToken() {
      
      authToken_ = getDefaultInstance().getAuthToken();
      onChanged();
      return this;
    }
    /**
     * <code>string auth_token = 1;</code>
     * @param value The bytes for authToken to set.
     * @return This builder for chaining.
     */
    public Builder setAuthTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authToken_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.emporiaenergy.protos.partnerapi.OutletStatus> outletStatus_ =
      java.util.Collections.emptyList();
    private void ensureOutletStatusIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        outletStatus_ = new java.util.ArrayList<com.emporiaenergy.protos.partnerapi.OutletStatus>(outletStatus_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.protos.partnerapi.OutletStatus, com.emporiaenergy.protos.partnerapi.OutletStatus.Builder, com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder> outletStatusBuilder_;

    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public java.util.List<com.emporiaenergy.protos.partnerapi.OutletStatus> getOutletStatusList() {
      if (outletStatusBuilder_ == null) {
        return java.util.Collections.unmodifiableList(outletStatus_);
      } else {
        return outletStatusBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public int getOutletStatusCount() {
      if (outletStatusBuilder_ == null) {
        return outletStatus_.size();
      } else {
        return outletStatusBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public com.emporiaenergy.protos.partnerapi.OutletStatus getOutletStatus(int index) {
      if (outletStatusBuilder_ == null) {
        return outletStatus_.get(index);
      } else {
        return outletStatusBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder setOutletStatus(
        int index, com.emporiaenergy.protos.partnerapi.OutletStatus value) {
      if (outletStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutletStatusIsMutable();
        outletStatus_.set(index, value);
        onChanged();
      } else {
        outletStatusBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder setOutletStatus(
        int index, com.emporiaenergy.protos.partnerapi.OutletStatus.Builder builderForValue) {
      if (outletStatusBuilder_ == null) {
        ensureOutletStatusIsMutable();
        outletStatus_.set(index, builderForValue.build());
        onChanged();
      } else {
        outletStatusBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder addOutletStatus(com.emporiaenergy.protos.partnerapi.OutletStatus value) {
      if (outletStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutletStatusIsMutable();
        outletStatus_.add(value);
        onChanged();
      } else {
        outletStatusBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder addOutletStatus(
        int index, com.emporiaenergy.protos.partnerapi.OutletStatus value) {
      if (outletStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutletStatusIsMutable();
        outletStatus_.add(index, value);
        onChanged();
      } else {
        outletStatusBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder addOutletStatus(
        com.emporiaenergy.protos.partnerapi.OutletStatus.Builder builderForValue) {
      if (outletStatusBuilder_ == null) {
        ensureOutletStatusIsMutable();
        outletStatus_.add(builderForValue.build());
        onChanged();
      } else {
        outletStatusBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder addOutletStatus(
        int index, com.emporiaenergy.protos.partnerapi.OutletStatus.Builder builderForValue) {
      if (outletStatusBuilder_ == null) {
        ensureOutletStatusIsMutable();
        outletStatus_.add(index, builderForValue.build());
        onChanged();
      } else {
        outletStatusBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder addAllOutletStatus(
        java.lang.Iterable<? extends com.emporiaenergy.protos.partnerapi.OutletStatus> values) {
      if (outletStatusBuilder_ == null) {
        ensureOutletStatusIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outletStatus_);
        onChanged();
      } else {
        outletStatusBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder clearOutletStatus() {
      if (outletStatusBuilder_ == null) {
        outletStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        outletStatusBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public Builder removeOutletStatus(int index) {
      if (outletStatusBuilder_ == null) {
        ensureOutletStatusIsMutable();
        outletStatus_.remove(index);
        onChanged();
      } else {
        outletStatusBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public com.emporiaenergy.protos.partnerapi.OutletStatus.Builder getOutletStatusBuilder(
        int index) {
      return getOutletStatusFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder getOutletStatusOrBuilder(
        int index) {
      if (outletStatusBuilder_ == null) {
        return outletStatus_.get(index);  } else {
        return outletStatusBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public java.util.List<? extends com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder> 
         getOutletStatusOrBuilderList() {
      if (outletStatusBuilder_ != null) {
        return outletStatusBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(outletStatus_);
      }
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public com.emporiaenergy.protos.partnerapi.OutletStatus.Builder addOutletStatusBuilder() {
      return getOutletStatusFieldBuilder().addBuilder(
          com.emporiaenergy.protos.partnerapi.OutletStatus.getDefaultInstance());
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public com.emporiaenergy.protos.partnerapi.OutletStatus.Builder addOutletStatusBuilder(
        int index) {
      return getOutletStatusFieldBuilder().addBuilder(
          index, com.emporiaenergy.protos.partnerapi.OutletStatus.getDefaultInstance());
    }
    /**
     * <pre>
     * should the outlet be set to on or off?
     * </pre>
     *
     * <code>repeated .protos.OutletStatus outlet_status = 2;</code>
     */
    public java.util.List<com.emporiaenergy.protos.partnerapi.OutletStatus.Builder> 
         getOutletStatusBuilderList() {
      return getOutletStatusFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.protos.partnerapi.OutletStatus, com.emporiaenergy.protos.partnerapi.OutletStatus.Builder, com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder> 
        getOutletStatusFieldBuilder() {
      if (outletStatusBuilder_ == null) {
        outletStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.emporiaenergy.protos.partnerapi.OutletStatus, com.emporiaenergy.protos.partnerapi.OutletStatus.Builder, com.emporiaenergy.protos.partnerapi.OutletStatusOrBuilder>(
                outletStatus_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        outletStatus_ = null;
      }
      return outletStatusBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.OutletStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.OutletStatusRequest)
  private static final com.emporiaenergy.protos.partnerapi.OutletStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.protos.partnerapi.OutletStatusRequest();
  }

  public static com.emporiaenergy.protos.partnerapi.OutletStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutletStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<OutletStatusRequest>() {
    @java.lang.Override
    public OutletStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutletStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutletStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutletStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.protos.partnerapi.OutletStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

