// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api.proto

package com.emporiaenergy.protos.partnerapi;

public interface OutletStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.OutletStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  java.lang.String getManufacturerDeviceId();
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes();

  /**
   * <code>bool on = 2;</code>
   * @return The on.
   */
  boolean getOn();
}
